// Code Templates for Shader Export

// Check if uniform is used in shader source
function uniformIsUsed(uniformName, vertSrc, fragSrc) {
  const pattern = new RegExp(`\\b${uniformName}\\b`);
  return pattern.test(vertSrc) || pattern.test(fragSrc);
}

// Check if shader uses alpha
function usesAlpha(fragSrc, presetCategory) {
  if (presetCategory === 'fx') return true;
  return /gl_FragColor\s*=\s*vec4\s*\([^,]+,[^,]+,[^,]+,\s*(0\.[0-9]+|[01])\s*\)/.test(fragSrc) ||
         fragSrc.includes('discard');
}

// Generate Three.js ShaderMaterial code
export function generateThreeJS(vertSrc, fragSrc, uniforms, presetCategory) {
  const usedUniforms = {};
  
  // Filter only used uniforms
  Object.entries(uniforms).forEach(([key, value]) => {
    if (uniformIsUsed(key, vertSrc, fragSrc)) {
      usedUniforms[key] = value;
    }
  });
  
  const isTransparent = usesAlpha(fragSrc, presetCategory);
  
  // Build uniform declarations
  const uniformDecls = Object.entries(usedUniforms).map(([key, value]) => {
    if (key === 'u_time') {
      return `  ${key}: { value: 0 }`;
    }
    if (key.startsWith('u_color')) {
      return `  ${key}: { value: new THREE.Color('${value}') }`;
    }
    return `  ${key}: { value: ${value} }`;
  }).join(',\n');
  
  return `// Generated by Shader Studio
import * as THREE from 'three';

const uniforms = {
${uniformDecls}
};

// Update u_time in your animation loop:
// uniforms.u_time.value += clock.getDelta();

const material = new THREE.ShaderMaterial({
  uniforms,
  vertexShader: \`
${vertSrc}
  \`,
  fragmentShader: \`
${fragSrc}
  \`,
  vertexColors: true,
  transparent: ${isTransparent},
  side: THREE.FrontSide,
});

export default material;`;
}

// Generate React Three Fiber code
export function generateR3F(vertSrc, fragSrc, uniforms, presetCategory) {
  const usedUniforms = {};
  
  Object.entries(uniforms).forEach(([key, value]) => {
    if (uniformIsUsed(key, vertSrc, fragSrc)) {
      usedUniforms[key] = value;
    }
  });
  
  const isTransparent = usesAlpha(fragSrc, presetCategory);
  const timeScale = uniforms.u_timeScale || 1.0;
  
  // Build uniform useMemo
  const uniformEntries = Object.entries(usedUniforms).map(([key, value]) => {
    if (key === 'u_time') {
      return `    ${key}: { value: 0 }`;
    }
    if (key.startsWith('u_color')) {
      return `    ${key}: { value: new THREE.Color('${value}') }`;
    }
    return `    ${key}: { value: ${value} }`;
  }).join(',\n');
  
  return `// Generated by Shader Studio
import { useMemo, useRef } from 'react';
import { useFrame } from '@react-three/fiber';
import * as THREE from 'three';

const vertexShader = \`
${vertSrc}
\`;

const fragmentShader = \`
${fragSrc}
\`;

export function ShaderMesh({ geometry, ...props }) {
  const matRef = useRef();

  const uniforms = useMemo(() => ({
${uniformEntries}
  }), []);

  useFrame((_, delta) => {
    if (matRef.current) {
      matRef.current.uniforms.u_time.value += delta * ${timeScale};
    }
  });

  return (
    <mesh geometry={geometry} {...props}>
      <shaderMaterial
        ref={matRef}
        vertexShader={vertexShader}
        fragmentShader={fragmentShader}
        uniforms={uniforms}
        vertexColors
        transparent={${isTransparent}}
      />
    </mesh>
  );
}`;
}

// Generate GLSL files content
export function generateGLSLFiles(vertSrc, fragSrc, uniforms) {
  const usedUniforms = {};
  
  Object.entries(uniforms).forEach(([key, value]) => {
    if (uniformIsUsed(key, vertSrc, fragSrc)) {
      usedUniforms[key] = value;
    }
  });
  
  // Generate uniforms.json
  const uniformsJson = {};
  Object.entries(usedUniforms).forEach(([key, value]) => {
    if (!key.startsWith('u_color')) {
      uniformsJson[key] = value;
    } else {
      uniformsJson[key] = value;
    }
  });
  
  const readme = `# Shader Files

Generated by Shader Studio

## Files

- \`vertex.glsl\` - Vertex shader source
- \`fragment.glsl\` - Fragment shader source
- \`uniforms.json\` - Uniform values

## Uniforms

${Object.entries(usedUniforms).map(([key, value]) => {
  if (key.startsWith('u_color')) {
    return `- \`${key}\`: ${value} (color)`;
  }
  return `- \`${key}\`: ${value}`;
}).join('\n')}

## Usage

### Three.js

\`\`\`javascript
import * as THREE from 'three';

const material = new THREE.ShaderMaterial({
  uniforms: {
    // Load values from uniforms.json
  },
  vertexShader: await fetch('vertex.glsl').then(r => r.text()),
  fragmentShader: await fetch('fragment.glsl').then(r => r.text()),
  vertexColors: true
});
\`\`\`

### Raw WebGL

Load the shader sources and compile them using \`gl.createShader()\` and \`gl.compileShader()\`.
`;

  return {
    vertex: vertSrc,
    fragment: fragSrc,
    uniforms: JSON.stringify(uniformsJson, null, 2),
    readme
  };
}

// Generate Vanilla WebGL code
export function generateVanillaWebGL(vertSrc, fragSrc, uniforms, presetCategory) {
  const usedUniforms = {};
  
  Object.entries(uniforms).forEach(([key, value]) => {
    if (uniformIsUsed(key, vertSrc, fragSrc)) {
      usedUniforms[key] = value;
    }
  });
  
  const isTransparent = usesAlpha(fragSrc, presetCategory);
  
  // Build uniform location getters and initial values
  const uniformLocations = Object.keys(usedUniforms).map(key => {
    return `const ${key} = gl.getUniformLocation(prog, '${key}');`;
  }).join('\n');
  
  const uniformSetters = Object.entries(usedUniforms).map(([key, value]) => {
    if (key === 'u_time') {
      return `  gl.uniform1f(${key}, t);`;
    }
    if (key.startsWith('u_color')) {
      const color = new THREE.Color(value);
      return `  gl.uniform3f(${key}, ${color.r.toFixed(3)}, ${color.g.toFixed(3)}, ${color.b.toFixed(3)});`;
    }
    return `  gl.uniform1f(${key}, ${value});`;
  }).join('\n');
  
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Shader Demo — Generated by Shader Studio</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { background: #0a0c10; overflow: hidden; }
    canvas { display: block; width: 100vw; height: 100vh; }
  </style>
</head>
<body>
<canvas id="c"></canvas>
<script>
// Note: Matrix uniforms, attribute buffers, and geometry setup are scaffolded.
// Plug in your own geometry or adapt for your engine.

const canvas = document.getElementById('c');
const gl = canvas.getContext('webgl');

// Resize
function resize() {
  canvas.width = window.innerWidth;
  canvas.height = window.innerHeight;
  gl.viewport(0, 0, canvas.width, canvas.height);
}
window.addEventListener('resize', resize);
resize();

// Enable depth testing
${isTransparent ? `gl.enable(gl.DEPTH_TEST);
gl.enable(gl.BLEND);
gl.blendFunc(gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA);` : `gl.enable(gl.DEPTH_TEST);`}

// Vertex shader
const vertSrc = \`
attribute vec3 position;
attribute vec3 normal;
attribute vec3 color;
uniform mat4 projectionMatrix;
uniform mat4 modelViewMatrix;
uniform mat3 normalMatrix;
${vertSrc}
\`;

// Fragment shader
const fragSrc = \`
precision mediump float;
${fragSrc}
\`;

// Compile shader
function compile(type, src) {
  const s = gl.createShader(type);
  gl.shaderSource(s, src);
  gl.compileShader(s);
  if (!gl.getShaderParameter(s, gl.COMPILE_STATUS)) {
    console.error(gl.getShaderInfoLog(s));
    throw new Error('Shader compile failed');
  }
  return s;
}

// Create program
const prog = gl.createProgram();
gl.attachShader(prog, compile(gl.VERTEX_SHADER, vertSrc));
gl.attachShader(prog, compile(gl.FRAGMENT_SHADER, fragSrc));
gl.linkProgram(prog);
gl.useProgram(prog);

// Get uniform locations
${uniformLocations}

// Animation loop
let t = 0;
function frame(now) {
  t = now * 0.001;
  
  // Set uniforms
${uniformSetters}
  
  gl.clearColor(0.04, 0.047, 0.063, 1.0);
  gl.clear(gl.COLOR_BUFFER_BIT | gl.DEPTH_BUFFER_BIT);
  
  // TODO: Bind your geometry and call gl.drawElements()
  // Example:
  // gl.bindBuffer(gl.ARRAY_BUFFER, positionBuffer);
  // gl.enableVertexAttribArray(positionLoc);
  // gl.vertexAttribPointer(positionLoc, 3, gl.FLOAT, false, 0, 0);
  // gl.drawElements(gl.TRIANGLES, indexCount, gl.UNSIGNED_SHORT, 0);
  
  requestAnimationFrame(frame);
}
requestAnimationFrame(frame);
<\/script>
</body>
</html>`;
}

// Download helper
export function downloadFile(content, filename, mimeType = 'text/plain') {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// Import Three.js Color for vanilla WebGL template
import * as THREE from 'three';
